# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lS_XuscwOnT-OWxvx2A_IqTYHOhG6khS
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

christ = cv2.imread("../data1/cristo.jpg")
noise0 = cv2.imread("../data1/ruido0.jpg")
noise1 = cv2.imread("../data1/ruido1.jpg")
noise2 = cv2.imread("../data1/ruido2.jpg")
noise3 = cv2.imread("../data1/ruido3.jpg")
noise4 = cv2.imread("../data1/ruido4.jpg")
noise5 = cv2.imread("../data1/ruido5.jpg")
noise6 = cv2.imread("../data1/ruido6.jpg")

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(christ)
ax2.hist(christ.flatten(), bins=255)

plt.plot()

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(noise0)
ax2.hist(noise0.flatten(), bins=255)

plt.plot()

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(noise1)
ax2.hist(noise1.flatten(), bins=255)

plt.plot()

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(noise2)
ax2.hist(noise2.flatten(), bins=255)

plt.plot()

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(noise3)
ax2.hist(noise3.flatten(), bins=255)

plt.plot()

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(noise4)
ax2.hist(noise4.flatten(), bins=255)

plt.plot()

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(noise5)
ax2.hist(noise5.flatten(), bins=255)

plt.plot()

plt.figure(figsize=(15,5))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
ax1.imshow(noise6)
ax2.hist(noise6.flatten(), bins=255)

plt.plot()

